job:
  image: hmctspublic.azurecr.io/div/cos:latest
  aadIdentityName: div
  keyVaults:
    div:
      secrets:
        - name: ccd-submission-s2s-auth-secret
          alias: AUTH_PROVIDER_CCDSUBMISSION_CLIENT_KEY
        - name: div-doc-s2s-auth-secret
          alias: AUTH_PROVIDER_DOCUMENTGENERATOR_CLIENT_KEY
        - name: idam-secret
          alias: IDAM_CLIENT_SECRET
        - name: idam-xui-secret
          alias: IDAM_XUI_CLIENT_SECRET
        - name: frontend-secret
          alias: SERVICE_AUTH_SECRET
        - name: idam-citizen-username
          alias: IDAM_CITIZEN_USERNAME
        - name: idam-citizen-password
          alias: IDAM_CITIZEN_PASSWORD
        - name: idam-caseworker-username
          alias: IDAM_CASEWORKER_USERNAME
        - name: idam-caseworker-password
          alias: IDAM_CASEWORKER_PASSWORD
        - name: uk-gov-notify-api-key
          alias: UK_GOV_NOTIFY_API_KEY
        - name: AppInsightsInstrumentationKey
          alias: azure.application-insights.instrumentation-key
        - name: app-insights-connection-string
          alias: app-insights-connection-string
        - name: spring-mail-password
          alias: spring.mail.password
        - name: idam-caseworker-superuser-username
          alias: IDAM_CASEWORKER_SUPERUSER_USERNAME
        - name: idam-caseworker-superuser-password
          alias: IDAM_CASEWORKER_SUPERUSER_PASSWORD
  environment:
    AUTH_PROVIDER_SERVICE_CLIENT_BASEURL: "http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    IDAM_API_URL: "https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net"
    PRD_API_URL: "http://rd-professional-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    IDAM_S2S_URL: "http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    FINREM_NOTIFICATION_SERVICE_BASE_URL: "http://finrem-ns-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    PAYMENT_SERVICE_API_BASEURL: "http://finrem-ps-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    ACA_SERVICE_API_BASEURL: "http://aac-manage-case-assignment-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    CCD_DATA_STORE_API_BASEURL: "http://ccd-data-store-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    IDAM_API_REDIRECT_URL: "https://finrem-frontend-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal/oauth2/callback"
    DOCUMENT_MANAGEMENT_STORE_URL: "http://dm-store-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    SEND_LETTER_SERVICE_BASEURL: "http://rpe-send-letter-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    PAYMENT_API_URL: "http://payment-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    FEES_API_URL: "http://fees-register-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    CASE_DOCUMENT_AM_URL: "http://ccd-case-document-am-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
  args:
    - run
    - SmeeAndFordExtractTask
  schedule: "0 0/10 * * *"
  concurrencyPolicy: Forbid
global:
  jobKind: CronJob
  environment: aat
